### PR TITLE
Add redirect

### PR DESCRIPTION
**Pull request by tomodachi94**
It appears this project hasn't been updated in 3 years. I maintain a [much more active Awesome list](https://github.com/tomodachi94/awesome-computercraft) with more content. This PR redirects users there.

Feel free to close this PR without merging; your list is the second result on DuckDuckGo, and I think it would be a good idea to just have one list.

### CODE REVIEW

**Comment by LakeYS** [comment]
Nice list. Looks good to me - glad to see there's another one that's more active.

**Comment by LakeYS** [comment]
Will archive this repo as-is in a few days if no more changes are needed.

**Comment by tomodachi94** [comment]
Yeah, I think that's the only major change that is needed @LakeYS.

**Comment by tomodachi94** [comment]
Btw, thank you for your work on this @LakeYS!

**Comment by LakeYS** [comment]
@tomodachi94 You as well! Happy to see there's still some Computercraft geeks out and about.

**Comment by tomodachi94** [comment]
> @tomodachi94 You as well! Happy to see there's still some Computercraft geeks out and about.

Us CC nerds have mostly congregated into the Discord server at https://computercraft.cc.

**Pull request merged**
